FW-5851-feather-logo
First-Peoples-Cultural-Council/fv-app pull request #144
Opened 2024-05-25 01:31 UTC by Cara-Barter

Description of Changes

- replaced png and svg images and sized header image

Checklist

- [ ] README / documentation has been updated if needed
- [x] PR title / commit messages contain Jira ticket number if applicable
- [ ] Tests have been updated / created if applicable

Reviewers Should Do The Following:

- [x] Review the changes here
- [ ] Pull the branch and test locally

Additional Notes
N/A

2024-05-27 15:59 UTC, gmcauliffe requested changes
These replacement logo images need to maintain a similar ratio of logo to background as the old images. Also we need to avoid distorting the aspect ratio of the logo itself when it is resized, for branding consistency. 

@sarahfirstvoices is this something Comms could assist us with?

2024-05-27 16:10 UTC, sarahfirstvoices commented on public/default/logo512.png
Looks like these smaller ones have been warped, compared to the original. Do you need help scaling them with the same aspect ratio?

2024-05-27 16:13 UTC, sarahfirstvoices requested changes
We'll need to fix the aspect ratio for the images in the default folder

2024-05-27 16:14 UTC, sarahfirstvoices commented
> @sarahfirstvoices is this something Comms could assist us with?

Mind meld. Yes probably

2024-05-28 16:52 UTC, sarahfirstvoices approved these changes

2024-05-28 17:13 UTC, gmcauliffe approved these changes

2024-05-28 17:24 UTC, merged